name: jax-unirep
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20211102.0
  - absl-py=1.0.0
  - alembic=1.7.7
  - alsa-lib=1.2.3.2
  - anyio=3.6.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astroid=2.11.5
  - attr=2.5.1
  - attrs=21.4.0
  - autopage=0.5.0
  - babel=2.10.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - black=22.3.0
  - bleach=5.0.0
  - brotlipy=0.7.0
  - bumpversion=0.5.3
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfgv=3.3.1
  - charset-normalizer=2.0.12
  - click=8.1.3
  - cliff=3.10.1
  - cmaes=0.8.2
  - cmarkgfm=0.8.0
  - cmd2=2.3.3
  - colorama=0.4.4
  - colorlog=6.6.0
  - commonmark=0.9.1
  - conda=4.12.0
  - conda-package-handling=1.8.1
  - coverage=6.3.3
  - cryptography=36.0.2
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.4
  - distlib=0.3.4
  - docutils=0.18.1
  - entrypoints=0.4
  - expat=2.4.8
  - fftw=3.3.10
  - filelock=3.7.0
  - flit-core=3.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - future=0.18.2
  - gettext=0.19.8.1
  - greenlet=1.1.2
  - grpc-cpp=1.45.2
  - gst-plugins-base=1.20.2
  - gstreamer=1.20.2
  - hypothesis=6.46.5
  - icu=70.1
  - identify=2.5.0
  - idna=3.3
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.7.1
  - iniconfig=1.1.1
  - ipykernel=6.13.0
  - ipython=7.33.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.0
  - isort=5.10.1
  - jack=1.9.18
  - jedi=0.18.1
  - jeepney=0.8.0
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9e
  - json-c=0.15
  - json5=0.9.5
  - jsonschema=4.5.1
  - jupyter=1.0.0
  - jupyter_client=7.3.1
  - jupyter_console=6.4.3
  - jupyter_core=4.10.0
  - jupyter_server=1.17.0
  - jupyterlab=3.4.2
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.13.0
  - jupyterlab_widgets=1.1.0
  - keyring=23.4.0
  - keyutils=1.6.1
  - krb5=1.19.3
  - lazy-object-proxy=1.7.1
  - ld_impl_linux-64=2.36.1
  - libblas=3.9.0
  - libcap=2.51
  - libcblas=3.9.0
  - libclang=14.0.3
  - libclang13=14.0.3
  - libcups=2.3.3
  - libdb=6.2.32
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.3.4
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.70.2
  - libgomp=12.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm14=14.0.3
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.20
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=14.3
  - libprotobuf=3.20.1
  - libsndfile=1.0.31
  - libsodium=1.0.18
  - libstdcxx-ng=12.1.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - mako=1.2.0
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.3
  - mccabe=0.7.0
  - mistune=0.8.4
  - multipledispatch=0.6.0
  - mypy_extensions=0.4.3
  - mysql-common=8.0.29
  - mysql-libs=8.0.29
  - nbclassic=0.3.7
  - nbclient=0.6.3
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nodeenv=1.6.0
  - notebook=6.4.11
  - notebook-shim=0.1.0
  - nspr=4.32
  - nss=3.77
  - openssl=1.1.1o
  - opt_einsum=3.3.0
  - optuna=2.10.0
  - packaging=21.3
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathlib=1.0.1
  - pathspec=0.9.0
  - pbr=5.9.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.1
  - pkginfo=1.8.2
  - platformdirs=2.5.1
  - pluggy=1.0.0
  - pre-commit=2.19.0
  - prettytable=3.3.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.29
  - prompt_toolkit=3.0.29
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=14.0
  - py=1.11.0
  - pycosat=0.6.3
  - pycparser=2.21
  - pydocstyle=6.1.1
  - pygments=2.12.0
  - pylint=2.13.9
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyperclip=1.8.2
  - pyprojroot=0.2.0
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - pytest=7.1.2
  - pytest-cov=3.0.0
  - python=3.7.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python-flatbuffers=2.0
  - python_abi=3.7
  - pytz=2022.1
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt-main=5.15.3
  - qtconsole=5.3.0
  - qtconsole-base=5.3.0
  - qtpy=2.1.0
  - re2=2022.04.01
  - readline=8.1
  - readme_renderer=35.0
  - regex=2022.4.24
  - requests=2.27.1
  - requests-toolbelt=0.9.1
  - rfc3986=2.0.0
  - rich=12.4.1
  - ruamel_yaml=0.15.80
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - secretstorage=3.3.2
  - send2trash=1.8.0
  - setuptools=62.2.0
  - sip=6.5.1
  - six=1.16.0
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sqlalchemy=1.4.36
  - sqlite=3.38.5
  - stevedore=3.5.0
  - terminado=0.13.3
  - threadpoolctl=3.1.0
  - tinycss2=1.1.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.2.0
  - twine=4.0.0
  - typed-ast=1.5.3
  - typing-extensions=4.2.0
  - typing_extensions=4.2.0
  - ukkonen=1.0.1
  - urllib3=1.26.9
  - virtualenv=20.14.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.2
  - wheel=0.37.1
  - widgetsnbextension=3.6.0
  - wrapt=1.14.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - biopython==1.79
    - cycler==0.11.0
    - feather-format==0.4.1
    - fonttools==4.33.3
    - ghp-import==2.1.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - jax==0.2.10
    - jax-unirep==2.1.0
    - jaxlib==0.1.60+cuda102
    - kiwisolver==1.4.2
    - markdown==3.3.7
    - matplotlib==3.5.2
    - mergedeep==1.3.4
    - mkautodoc==0.1.0
    - mkdocs==1.3.0
    - mkdocs-material==8.2.15
    - mkdocs-material-extensions==1.0.3
    - mknotebooks==0.7.1
    - numpy==1.19.5
    - pandas==1.3.5
    - pandoc-eqnos==2.5.0
    - pandoc-fignos==2.4.0
    - pandoc-secnos==2.2.2
    - pandoc-tablenos==2.3.0
    - pandoc-xnos==2.5.0
    - pillow==9.1.1
    - pyarrow==8.0.0
    - pymdown-extensions==9.4
    - pyyaml-env-tag==0.1
    - seaborn==0.11.2
    - smmap==5.0.0
    - watchdog==2.1.8
